import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FooterComp from "@/components/Footer";
import Script from "next/script";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "PK Taxes, Accounting & Legal Services",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="/crisp.js" />
      </head>
      <body className={inter.className}>
        <main className="max-w-7xl mx-auto">
          <Navbar />
          {children}
          <FooterComp />
        </main>
      </body>
    </html>
  );
}
